// Generated by build:cloudflare; never imported by the standard Next.js build.
import handler from '../.open-next/worker.js'
import { previewHandler } from './preview.mjs'

export default previewHandler(handler)
